services:
  db:
    image: mysql:9.2
    container_name: ai_planning_project_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ai_planning_project
      MYSQL_USER: planner
      MYSQL_PASSWORD: plannerpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/data
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --local-infile=1 --secure-file-priv="/data"